### ISSUE TITLE
Does samba-4.17.6 support compiling and packaging in centos7 environment?

### ISSUE THREAD

**Issue by Tu-qiu** [nkadel/samba-4.13.x-srpm#5]
Compiling in the centos7 environment lacks the following dependencies:
error: Failed build dependencies:
         gnutls-devel >= 3.4.7 is needed by samba-0:4.17.6-109.el7.x86_64
         mingw32-gcc is needed by samba-0:4.17.6-109.el7.x86_64
         mingw64-gcc is needed by samba-0:4.17.6-109.el7.x86_64
         rpcgen is needed by samba-0:4.17.6-109.el7.x86_64
         rpcsvc-proto-devel is needed by samba-0:4.17.6-109.el7.x86_64
         python36-pyasn1 >= 0.4.8 is needed by samba-0:4.17.6-109.el7.x86_64
         libtalloc-devel >= 2.3.4 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-talloc-devel >= 2.3.4 is needed by samba-0:4.17.6-109.el7.x86_64
         libtevent-devel >= 0.13.0 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-tevent >= 0.13.0 is needed by samba-0:4.17.6-109.el7.x86_64
         libtdb-devel >= 1.4.7 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-tdb >= 1.4.7 is needed by samba-0:4.17.6-109.el7.x86_64
         libldb-devel >= 2.6.1 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-ldb >= 2.6.1 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-ldb-devel >= 2.6.1 is needed by samba-0:4.17.6-109.el7.x86_64
         python36-gpg is needed by samba-0:4.17.6-109.el7.x86_64
         tdb-tools is needed by samba-0:4.17.6-109.el7.x86_64
         ldb-tools is needed by samba-0:4.17.6-109.el7.x86_64
make: *** [build] Error 1

**Comment by nkadel** [comment]
You should be using my wrapper for this, the "samba4repo" repository with the git submodules for building samba itself and other libraries.

I gave up on RHEL 7.x compatible releases some time ago, precisely because of the gnutls requirements.

RHEL makes some choices about building sssd and their supported FreeIPA tools rather than the upstream Samba and Samba published libraries that have been.... awkward to integrate for Samba updates. Use CentOS 8 or later for Samba servers. The integrated "sssd" support is enough for nearly all clients, though it's built on top of the underlying Samba libraries like libldb and libtalloc.

**Comment by nkadel** [comment]
Use RHEL 8 or later, and build Samba inside https://github.com/nkadel/samba4repo
